/* Nagamese for the HatiAlert interface. DRAFT: written without a native
   speaker's review, so please have the Wokha forest office or a Nagamese
   speaker check it. Phrases marked "(original)" come from the original app.

   How it works: app.js shows English by default. When Nagamese is chosen,
   every piece of interface text that exactly matches a key in `words` is
   swapped for its value, and `patterns` handle text with numbers or names in
   it ({1}, {2} = the parts in brackets; those parts are translated too when
   they match a word). Anything not listed stays in English, and text people
   type (alert messages, notes, names) is never changed.

   To fix a phrase, edit the text on the right-hand side and reload. */
window.HATI_NAGAMESE = {
  words: {
    // navigation and roles
    "Home": "Ghor",
    "Report": "Report",
    "Cases": "Case khan",
    "My reports": "Moi laga report",
    "Alerts": "Alert",
    "More": "Aru",
    "Villager": "Gaon manu",
    "Forest guard": "Jongol guard",
    "Forest officer": "Jongol officer",
    "Main": "Mukhyo",

    // start-up and loading
    "Loading…": "Load hoi ase…",
    "Starting HatiAlert…": "HatiAlert khuli ase…",
    "Starting Python in your browser…": "Python khuli ase…",
    "Loading HatiAlert…": "HatiAlert load hoi ase…",
    "HatiAlert couldn't start": "HatiAlert khula nohol",
    "Reload": "Aru ekbar load koribi",
    "That didn't load": "Etu load nohol",
    "Try again": "Aru ekbar try koribi",

    // sign in and register
    "See elephants? Warn your village in a minute.": "Hati dikhise? Ek minute te gaon ke khobor dibi.",
    "Report sightings and crop raids, follow what the forest staff do about them, and get warnings for your village.": "Hati dikha aru kheti barbad laga report koribi, jongol staff ki kori ase dikhibi, aru apuni laga gaon nimite sabdhan khobor pabi.",
    "Sign in": "Login koribi",
    "Mobile number": "Mobile number",
    "New here?": "Notun ase?",
    "Create an account": "Account bonabi",
    "Try a demo account": "Demo account te try koribi",
    "Each role sees a different app. Tap one to fill in the form.": "Kaam hisab te app alag dikhe. Ekta te tipibi, form nijor pora bhoribo.",
    "← Sign in": "← Login",
    "Your village sets which warnings you get.": "Apuni laga gaon hisab te sabdhan khobor ahibo.",
    "Full name": "Pura naam",
    "Village": "Gaon",
    "Choose a PIN": "PIN ekta basibi",
    "4 to 6 digits": "4 pora 6 ta number",
    "Repeat PIN": "PIN aru ekbar dibi",
    "Create account": "Account bonabi",
    "New accounts start as villagers. Forest staff accounts are set up by the forest office.": "Notun account gaon manu hisab te khule. Jongol staff laga account forest office pora bonai dibo.",
    "The two PINs don't match.": "Duita PIN eke nohoi.",
    "Account created": "Account bonai dise",

    // home
    "No open incidents near you": "Apuni usor te khula ghotona nai",
    "All quiet across the district. You'll see new reports here.": "District te sab thik ase. Notun report ide dikhibo.",
    "Report elephants": "Hati laga report koribi",
    "Snap a photo and report": "Photo tulibi aru report koribi",
    "Open in district": "District te khula",
    "Waiting for a check": "Check nimite rukhi ase",
    "Reported in 24 h": "24 ghonta te report",
    "Sample incidents are loaded so you can try the app.": "App try koribole nimite sample ghotona rakhise.",
    "Remove sample data": "Sample data hatai dibi",
    "Delete all sample incidents and alerts?": "Sab sample ghotona aru alert hatai dibo?",
    "Delete": "Hatai dibi",
    "Keep": "Rakhibi",
    "Sample data removed": "Sample data hatai dise",
    "just now": "etiya-he",

    // incident types (original)
    "Elephant sighted": "Hati dekha",
    "Herd moving": "Pal jaache",
    "Crop raid": "Kheti barbad",
    "Property damage": "Ghar tuta",
    "Person injured": "Manuh ahata",
    "Person killed": "Manuh mara",

    // severity, status, alert type
    "Severity": "Khotra kiman",
    "Critical": "Bisi khotra",
    "High": "Dangor",
    "Medium": "Majot",
    "Low": "Kom",
    "Critical severity": "Bisi khotra",
    "High severity": "Dangor khotra",
    "Medium severity": "Majot khotra",
    "Low severity": "Kom khotra",
    "Reported": "Report hoise",
    "Verified": "Check kora hoise",
    "Team responded": "Team ahi gaise",
    "Resolved": "Shesh hoise",
    "False report": "Misa report",
    "reported": "report hoa",
    "verified": "check kora",
    "team responded": "team ahi gaise",
    "resolved": "shesh hoa",
    "false report": "misa report",
    "Update": "Notun khobor",
    "Elephant warning": "Hati sabdhan",
    "Information": "Khobor",
    "All clear": "Ebe thik ase",
    "Active": "Etiya cholise",

    // report form
    "Only \"what happened\" is required. Send it now and add detail if you can.": "Khali \"ki hoise\" to lagibo. Etiya pathai dibi, aru pare to bisi khobor dibi.",
    "What's happening?": "Ki hoi ase?",
    "Photo and voice note": "Photo aru awaz",
    "Optional. Take photos only from a safe distance. Never go closer to a herd for a picture.": "Dibo nalage bhi thik ase. Photo khali dur pora tulibi. Photo nimite hati laga usor te kitia bhi na-jabi.",
    "Take photo": "Photo tulibi",
    "From gallery": "Gallery pora",
    "Record voice note": "Awaz record koribi",
    "Stop and keep": "Bondh koribi aru rakhibi",
    "How many elephants?": "Kiman ta hati ase?",
    "A best guess is fine. Count calves too.": "Andaj te bhi thik ase. Bacha hati bhi gintibi.",
    "One fewer": "Ekta kom",
    "One more": "Ekta bisi",
    "Number of elephants": "Hati kiman ta",
    "Where?": "Kote?",
    "Nearest village": "Usor laga gaon",
    "How far from the village, and which way?": "Gaon pora kiman dur, aru kun phale?",
    "Distance from village": "Gaon pora kiman dur",
    "At the village": "Gaon te he",
    "Direction from the village": "Gaon pora kun phale",
    "village": "gaon",
    "Use my GPS location instead": "Moi laga GPS jaga use koribi",
    "Use village instead": "Gaon use koribi",
    "This device can't share its location.": "Etu phone pora jaga pathabo napare.",
    "Finding you…": "Apuni kot ase bisari ase…",
    "Location isn't available here. Use the village and direction instead.": "Ide jaga napai. Gaon aru phale use koribi.",
    "Landmark": "Chinto jaga",
    "(optional)": "(dibo nalage bhi thik)",
    "e.g. paddy fields below the church": "jene, girja tolote dhan kheti",
    "Which way are they moving?": "Hati khan kun phale jai ase?",
    "Not moving / not sure": "Jai thaka nai / thik napai",
    "Damage and injuries": "Nuksan aru ghao",
    "People hurt or killed": "Manu ghao aru mora",
    "Crops damaged (acres)": "Kheti nuksan (acre)",
    "Property loss (₹, estimate)": "Sompoti nuksan (₹, andaj)",
    "Anything else?": "Aru kiba ase?",
    "Calves with the herd, which fields, who is at risk…": "Dol te bacha ase, kun kheti, kun manu khotra te ase…",
    "Choose what happened": "Ki hoise etu basibi",
    "Send report": "Report pathai dibi",
    "Sending…": "Pathai ase…",
    "Report sent": "Report pathai dise",
    "Thank you. Your report number is": "Dhonyobad. Apuni laga report number:",
    "A forest guard will check it. Keep this number for any compensation claim.": "Jongol guard etu check koribo. Khotipuron mangibole nimite etu number rakhibi.",
    "Stay well away from the herd and warn your neighbours.": "Hati dol pora bisi dur te thakibi aru osorkhan ke khobor dibi.",
    "View report": "Report dikhibi",
    "Back to home": "Ghor te wapas",
    "Photo added": "Photo lagai dise",
    "Voice note added": "Awaz lagai dise",
    "That photo couldn't be opened. Try a JPEG or PNG.": "Etu photo khula nohol. JPEG ba PNG try koribi.",
    "Camera": "Camera",
    "Close camera": "Camera bondh koribi",
    "Switch camera": "Camera bodli koribi",
    "Retake": "Aru ekbar tulibi",
    "Use photo": "Etu photo lobi",
    "Photo you just took": "Etiya tula photo",
    "Couldn't switch camera": "Camera bodli nohol",
    "Remove photo": "Photo hatai dibi",
    "Remove": "Hatai dibi",
    "Photo": "Photo",
    "Report photo": "Report laga photo",
    "Close": "Bondh koribi",
    "File unavailable": "File nai",
    "photo": "photo",
    "voice note": "awaz",
    "photos": "photo",
    "voice notes": "awaz",

    // cases
    "Check new reports first. Oldest unchecked cases need attention.": "Prothom notun report check koribi. Check nokora puran case age dikhibi.",
    "Follow what the forest staff are doing about your reports.": "Apuni laga report nimite jongol staff ki kori ase dikhibi.",
    "Status": "Status",
    "Open": "Khula",
    "Closed": "Bondh",
    "All": "Sab",
    "Filter by village": "Gaon hisab te basibi",
    "All villages": "Sab gaon",
    "Nothing here": "Ide eku nai",
    "No cases match this filter.": "Etu hisab te case nai.",
    "Reports you send will appear here.": "Apuni pathai report ide dikhibo.",
    "← Cases": "← Case khan",
    "← My reports": "← Moi laga report",
    "Sample": "Sample",
    "Elephants": "Hati",
    "Heading": "Kun phale",
    "Not given": "Diya nai",
    "Location": "Jaga",
    "People hurt": "Manu ghao",
    "Crops": "Kheti",
    "Property loss": "Sompoti nuksan",
    "Reported by": "Report kora manu",
    "Photos and voice notes": "Photo aru awaz",
    "None yet.": "Etiya tak nai.",
    "Add photo": "Photo lagabi",
    "What has happened": "Ki ki hoise",
    "Staff action": "Staff laga kaam",
    "Note": "Likha",
    "(team sent, damage seen, advice given)": "(team pathaise, nuksan dikhise, upodesh dise)",
    "Mark verified": "Check kora hoise bulibi",
    "Mark team responded": "Team ahi gaise bulibi",
    "Close as resolved": "Shesh hoise kori bondh koribi",
    "Mark false report": "Misa report bulibi",
    "Add note only": "Khali likha lagabi",
    "Tell villages within 5 km.": "5 km bhitor laga gaon ke khobor dibi.",
    "Warn nearby villages": "Usor laga gaon ke sabdhan dibi",
    "Status updated": "Status bodli hoise",
    "Note added": "Likha lagai dise",

    // alerts
    "Send an alert": "Alert pathabi",
    "to chosen villages": "basi luwa gaon nimite",
    "Alert type": "Alert laga rokom",
    "Villages": "Gaon khan",
    "Message": "Khobor",
    "What is happening, where, and what people should do": "Ki hoi ase, kote, aru manu khan ki koribo lage",
    "Send alert": "Alert pathai dibi",
    "View case": "Case dikhibi",
    "No alerts yet": "Etiya tak alert nai",
    "Warnings for your village will show here.": "Apuni laga gaon laga sabdhan ide dikhibo.",
    "Alert sent": "Alert pathai dise",

    // district overview
    "← More": "← Aru",
    "District overview": "District laga hisab",
    "Period": "Somoy",
    "Export CSV": "CSV bahar koribi",
    "Incidents": "Ghotona",
    "Median time to respond": "Ahibole laga majot somoy",
    "Recorded losses": "Likha nuksan",
    "Incidents per day": "Din hisab te ghotona",
    "Hotspot villages": "Bisi ghotona hoa gaon",
    "What happened": "Ki hoise",
    "No incidents in this period.": "Etu somoy te ghotona nai.",
    "Download": "Download",
    "Copy": "Copy",
    "CSV export": "CSV",
    "Copied": "Copy hoise",
    "Press Ctrl+C or long-press to copy": "Copy koribole Ctrl+C ba dangor kori tipibi",

    // safety and help (original Nagamese where the original app had it)
    "Safety and help": "Bachibole aru modot",
    "Do": "Koribole",
    "Don't": "Na-koribole",
    "Keep well back from the herd and stay downwind": "Hati dol pora bisi dur te thakibi, aru hawa hati phale pora apuni phale ahi thaka jaga te thakibi",
    "Stay together in groups": "Ekelog te thakibi",
    "Make noise only from a safe distance (pots, horns)": "Dhur para awaz koribi",
    "Warn neighbours at once": "Osorkhan ke jaldi khobor dibi",
    "Report in HatiAlert straight away": "HatiAlert te jaldi report koribi",
    "Approach the herd or stop to take photos": "Photo lobole osorte na-jabi",
    "Block or corner an elephant's path": "Hati laga rasta na-bondh koribi",
    "Throw crackers near calves; it can panic the herd": "Bacha osorte bom na-phutabi",
    "Go to the fields alone at night during an alert": "Rati kheti te akela na-jabi",
    "Store rice beer or grain where a herd can reach it": "Hati pahibo para jaga te mod ba dhan na-rakhibi",
    "Emergency numbers": "Bipod laga number",
    "Placeholder, not a real line": "Namuna, asol number nohoi",
    "National emergency": "Desh laga bipod number",
    "Police, fire, ambulance": "Police, jui, ambulance",
    "Ambulance": "Ambulance",
    "Emergency medical": "Bipod laga dawai",
    "Police": "Police",
    "Police control room": "Police control room",
    "Forest control room, Wokha": "Jongol control room, Wokha",
    "24/7 forest helpline": "24 ghonta jongol helpline",
    "Compensation (ex-gratia)": "Khotipuron (ex-gratia)",
    "Human death": "Manu mora",
    "Permanent disability": "Hodai laga pongu",
    "Grievous injury": "Bisi ghao",
    "Simple injury": "Olop ghao",
    "Crop damage": "Kheti nuksan",
    "House damage": "Ghor nuksan",
    "As assessed by the range officer": "Range officer hisab kori dibo",
    "As assessed (replacement cost)": "Hisab kori dibo (notun bonabole laga khoroch)",
    "Amounts carried over from the original app. Confirm current rates with the Wokha Forest Division before filing.": "Etu poisa puran app pora loise. Mangibole age Wokha Forest Division te etiya laga rate puchibi.",
    "How to claim": "Kene mangibo",
    "Report the incident within 24 hours and note the HA- report number": "24 ghonta bhitor te report koribi aru HA- report number likhi rakhibi",
    "A forest guard verifies and records the damage": "Jongol guard nuksan check kori likhibo",
    "Submit the claim form at the Wokha Range Office": "Wokha Range Office te claim form jomai dibi",
    "Payment follows verification": "Check pichete poisa dibo",
    "Bring": "Loi ahibi",
    "Medical certificate (injuries)": "Doctor laga certificate (ghao nimite)",
    "Land record (crop damage)": "Mati laga kagoj (kheti nuksan nimite)",

    // more / settings
    "Trends, hotspots, response times, CSV export": "Ghotona hisab, bisi hoa gaon, ahibole somoy, CSV",
    "What to do, emergency numbers, compensation": "Ki koribo, bipod number, khotipuron",
    "Theme": "Rong",
    "Follows your phone's light or dark mode": "Phone laga light ba dark mode hisab te cholibo",
    "Bright, for outdoors in daylight": "Pohor, din te bahar nimite",
    "Black and grey, less glare at night": "Kola aru dhuli rong, rati te chokhu nimite bhal",
    "Deep blue with sky-blue buttons": "Gaar nila, akash nila button",
    "Your settings": "Apuni laga setting",
    "Name": "Naam",
    "Home village": "Nijor gaon",
    "Show incidents within": "Kiman dur tak ghotona dikhibo",
    "Save": "Save koribi",
    "Saved": "Save hoise",
    "Sign out": "Logout koribi",

    // map
    "Map of Wokha district. Use plus and minus keys to zoom, arrow keys to move.": "Wokha district laga map. Dangor/saru koribole + aru − tipibi, ghuribole arrow tipibi.",
    "Map of villages and open incidents": "Gaon aru khula ghotona laga map",
    "Zoom in": "Dangor koribi",
    "Zoom out": "Saru koribi",
    "Fit to area": "Pura jaga dikhibi",
    "Village, position not verified": "Gaon, jaga check kora nai",
    "Stream": "Nodi aru nala",
    "Contour, 100 m": "Unchai rekha, 100 m",
    "District boundary": "District laga sima",

    // messages from the server
    "Enter a number.": "Number dibi.",
    "This field is required.": "Etu bhoribo lagibo.",
    "Choose a village from the list.": "List pora gaon basibi.",
    "Attach a photo or a voice note.": "Photo ba awaz lagabi.",
    "That file didn't upload properly. Try again.": "File thik pora upload nohol. Aru ekbar try koribi.",
    "That file is empty.": "Etu file khali ase.",
    "Use a JPEG, PNG or WebP photo.": "JPEG, PNG ba WebP photo dibi.",
    "Use a recording in MP3, M4A, WebM, Ogg or WAV.": "MP3, M4A, WebM, Ogg ba WAV laga awaz dibi.",
    "Enter a 10-digit mobile number.": "10 ta number laga mobile number dibi.",
    "Sign in to continue.": "Agia jabole login koribi.",
    "Only forest staff can do this.": "Khali jongol staff etu koribo pare.",
    "Only forest officers can do this.": "Khali jongol officer etu koribo pare.",
    "Choose what happened.": "Ki hoise etu basibi.",
    "Choose a direction from the list.": "List pora phale basibi.",
    "Say which way from the village.": "Gaon pora kun phale etu kobi.",
    "That phone number and PIN don't match.": "Phone number aru PIN mila nai.",
    "Enter your full name.": "Pura naam dibi.",
    "Choose a PIN of 4 to 6 digits.": "4 pora 6 ta number laga PIN basibi.",
    "This number is already registered. Sign in instead.": "Etu number age pora register ase. Login koribi.",
    "Only forest staff can see closed cases.": "Khali jongol staff bondh case dikhibo pare.",
    "No incident with that number.": "Etu number laga ghotona nai.",
    "Choose a new status or write a note.": "Notun status basibi ba likha dibi.",
    "Only a forest officer can close a case.": "Khali jongol officer case bondh koribo pare.",
    "Only the reporter or forest staff can add to this case.": "Khali report kora manu ba jongol staff etu case te lagabo pare.",
    "That file is no longer available.": "Etu file etiya nai.",
    "Choose an alert type.": "Alert laga rokom basibi.",
    "Pick at least one village.": "Kom pora kom ekta gaon basibi.",
    "Can't reach HatiAlert. Check your connection and try again.": "HatiAlert te jabo para nai. Network check kori aru ekbar try koribi.",
    "Something went wrong.": "Kiba bhul hoise.",
  },

  // [English pattern, Nagamese]. Patterns match the whole text.
  patterns: [
    ["Elephant warning · (.+)", "Hati sabdhan · {1}"],
    ["Within (.+) km of (.+)", "{2} pora {1} km bhitor te"],
    ["(\\d+) open incidents? near you", "Apuni usor te {1} ta khula ghotona ase"],
    ["(\\d+) open incidents? elsewhere in the district\\. You'll see new reports here\\.", "District te dusra jaga {1} ta khula ghotona ase. Notun report ide dikhibo."],
    ["([\\d.]+) km ([NESW]{1,2}) of (.+)", "{3} pora {2} phale {1} km"],
    ["· (\\d+) elephants?", "· {1} ta hati"],
    ["(\\d+) min ago", "{1} minute age"],
    ["(\\d+) h ago", "{1} ghonta age"],
    ["(\\d+) days? ago", "{1} din age"],
    ["of (\\d+):00", "{1}:00 tak"],
    ["([\\d.]+) km away", "{1} km dur"],
    ["Using (.+), (.+) \\(±(\\d+) m\\)", "{1}, {2} use kori ase (±{3} m)"],
    ["(\\d+) (photos?), (\\d+) (voice notes?)", "{1} ta {2}, {3} ta {4}"],
    ["(\\d+) cases?", "{1} ta case"],
    ["([\\d.]+) acres", "{1} acre"],
    ["Warnings from forest staff\\. Alerts for (.+) are marked\\.", "Jongol staff laga sabdhan. {1} laga alert chinto kori dise."],
    ["(\\d+) days", "{1} din"],
    ["(\\d+) still open", "{1} ta etiya bhi khula"],
    ["across (\\d+) cases?", "{1} ta case te"],
    ["(\\d+) false reports?", "{1} ta misa report"],
    ["crops · (.+) property", "kheti · {1} sompoti"],
    ["CSV · last (\\d+) days", "CSV · sesh {1} din"],
    ["(.+): (\\d+) incidents?", "{1}: {2} ta ghotona"],
    ["Copy (.+) number", "{1} laga number copy koribi"],
    ["Theme: (.+)", "Rong: {1}"],
    ["Language: (.+)", "Bhasa: {1}"],
    ["Engine: (.+)", "Engine: {1}"],
    ["View photo (\\d+)", "Photo {1} dikhibi"],
    ["Voice note (\\d+)", "Awaz {1}"],
    ["Your (\\d+) km alert area", "Apuni laga {1} km alert jaga"],
    ["(.+): position not verified", "{1}: jaga check kora nai"],
    ["Enter a value from (.+) to (.+)\\.", "{1} pora {2} tak number dibi."],
    ["Keep this under (\\d+) characters\\.", "{1} letter pora kom likhibi."],
    ["Each (photo|voice note) must be under (.+) MB\\.", "Ekta {1} {2} MB pora kom hobo lage."],
    ["A report can have up to (\\d+) (photos|voice notes)\\.", "Ekta report te {1} ta {2} tak dibo pare."],
    ["Too many wrong PINs\\. Try again in (\\d+) min\\.", "Bisi bar bhul PIN dise. {1} minute pichete try koribi."],
    ["A (.+) case can't move to that status\\.", "{1} case etu status te jabo napare."],
  ],
};
